name: /scratch/gilbreth/zoellner/conda/envs/guided_rl
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=5_kmp_llvm
  - absl-py=2.3.1=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - appdirs=1.4.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - brotli=1.2.0=h41a2e66_0
  - brotli-bin=1.2.0=hf2c8021_0
  - brotli-python=1.2.0=py311h7c6b74e_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - cloudpickle=3.1.1=py311h06a4308_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.2=py311hd18a35c_0
  - cpython=3.11.14=py311hd8ed1ab_2
  - cuda-version=11.3=hbc958af_3
  - cudatoolkit=11.3.1=hb98b00a_13
  - cudnn=8.9.7.29=hbc23b4c_3
  - cupti=11.3.1=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.16=py311hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - farama-notifications=0.0.4=py311h06a4308_0
  - filelock=3.20.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - future=1.0.0=pyhd8ed1ab_2
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glfw=3.4=hb03c661_1
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - grpcio=1.54.2=py311hcafe171_0
  - gymnasium=0.29.1=py311h781c19f_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - idna=3.11=pyhd8ed1ab_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.6.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jax-jumpy=1.0.0=py311h06a4308_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h0aef613_1
  - libabseil=20230125.0=cxx17_hcb278e6_1
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.2.0=h09219d5_0
  - libbrotlidec=1.2.0=hd53d788_0
  - libbrotlienc=1.2.0=h02bd7ab_0
  - libcblas=3.9.0=16_linux64_mkl
  - libccd-double=2.1=h59595ed_3
  - libdeflate=1.22=hb9d3cd8_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libglvnd=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=h767d61c_7
  - libgrpc=1.54.2=hcf146ea_0
  - libhwloc=2.12.1=default_h3d81e11_1000
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.9.0=16_linux64_mkl
  - libmagma=2.7.2=h09159a4_2
  - libmagma_sparse=2.7.2=h09159a4_3
  - libmujoco=2.3.3=h5c724c8_0
  - libnsl=2.0.0=h5eee18b_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopengl-devel=1.7.0=ha4b6fd6_2
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=3.21.12=hfc55251_2
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libtiff=4.7.0=he137b08_1
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=20.1.8=h4922eb0_0
  - lodepng=20220109=h924138e_0
  - magma=2.7.2=h2cf16e7_3
  - markdown=3.10=pyhcf101f3_1
  - markupsafe=3.0.3=py311h3778330_0
  - matplotlib-base=3.10.7=py311h0f3be63_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2022.2.1=h6508926_16999
  - mkl-service=2.4.0=py311hb711fc7_0
  - mkl_fft=1.3.8=py311h8e1fd07_0
  - mkl_random=1.2.4=py311h2d0063b_2
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - mujoco=2.3.3=ha770c72_0
  - mujoco-python=2.3.3=py311h67b707b_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - ninja=1.13.1=h171cf75_0
  - numpy=1.26.4=py311h64a7726_0
  - openjpeg=2.5.3=h55fea9a_1
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hed34c8f_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311h98278a2_3
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - protobuf=4.21.12=py311hcafe171_0
  - psutil=7.0.0=py311hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.12.3=pyh3cfb1c2_0
  - pydantic-core=2.41.4=py311h902ca64_0
  - pyglfw=2.10.0=pyha770c72_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyopengl=3.1.10=pyha804496_2
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.0.0=cpu_mkl_py311hd1ebf82_101
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py311h3778330_0
  - pyzmq=27.1.0=py311hcf8288c_0
  - qhull=2020.2=h434a139_5
  - re2=2023.02.02=hcb278e6_0
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=pyhd8ed1ab_0
  - sentry-sdk=2.43.0=pyhd8ed1ab_0
  - setproctitle=1.3.6=py311h49ec1c0_1
  - setuptools=80.9.0=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=ha0421bc_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - sqlite=3.50.2=hb25bd0a_1
  - stable-baselines3=2.3.2=pyhd8ed1ab_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hb60516a_3
  - tbb-devel=2021.13.0=h74b38a2_3
  - tensorboard=2.20.0=pyhe01879c_0
  - tensorboard-data-server=0.7.0=py311h8488d03_3
  - tinyxml2=9.0.0=h9c3ff4c_2
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py311h5eee18b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.15.0=py311h06a4308_0
  - typing-inspection=0.4.2=pyhd8ed1ab_0
  - typing_extensions=4.15.0=py311h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wandb=0.22.3=py311hcc66767_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py311h06a4308_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.25.0=py311haee01d2_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - imageio-ffmpeg==0.6.0
      - moviepy==2.2.1
      - proglog==0.1.12
      - python-dotenv==1.2.1
      - tqdm==4.67.1
prefix: /scratch/gilbreth/zoellner/conda/envs/guided_rl
